apiVersion: apps/v1
kind: Deployment
metadata:
  name: path-change-deployment
  namespace: path-change
  labels:
    app: path-change
spec:
  replicas: 2
  selector:
    matchLabels:
      app: path-change
  template:
    metadata:
      labels:
        app: path-change
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
