apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.2" # Latest stable as of now
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  interval: 1h
  install:
    crds: CreateReplace # Critical for cert-manager
  values:
    crds:
      enabled: true
