apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: python-script
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: python
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: python
              tag: "3.11-slim"
            # Keeps the container running so you can exec in
            command: ["/bin/sh", "-c", "python3 -c 'import time; while True: print(\"Python is running...\"); time.sleep(60)'"]
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
