apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 30m
  chart:
    spec:
      chart: wordpress
      version: "28.1.9"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: wordpress # Adjust if your 'bitnami' repo is in another namespace
  values:
    # 1. Re-enable internal MariaDB (Default is true, but explicitly set for clarity)
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: false # Set to true if you have a default StorageClass

    # 2. WordPress Persistence
    persistence:
      enabled: false # Set to true if you have a default StorageClass

    # 3. Service Configuration
    service:
      type: ClusterIP

    # 4. Probes to fix "Connection Refused"
    # Gives WordPress and MariaDB extra time to complete initial handshake
    replicaCount: 5 
    readinessProbe:
      enabled: true
      initialDelaySeconds: 90 
      periodSeconds: 10
      failureThreshold: 6
    
    livenessProbe:
      enabled: true
      initialDelaySeconds: 180
      periodSeconds: 20

    # 5. Security Context (Bitnami images run as non-root on 8080)
    containerPorts:
      http: 8080
