apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-server
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx
      version: "22.5.0" # Latest stable as of Feb 2026
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx
  install:
    remediation:
      retries: 3
  values:
    # Minimal config for 'Ready' state
    service:
      type: ClusterIP
